### ISSUE TITLE
Error when typing

### ISSUE THREAD

**Issue by rugk** [wooorm/atom-linter-alex#11]
I just wrote a simple markdown file and when I was (vertically) near the end of the screen/browser window these error popped up two times. Every time I want to write more after this the error appears again.

```
Error: Got both html and text fields on Linter Response, expecting only one
  at D:\Users\%username%\.atom\packages\linter\lib\validate.coffee:33:19
  at Array.forEach (native)
  at Object.module.exports.Validate.messages (D:\Users\%username%\.atom\packages\linter\lib\validate.coffee:26:14)
  at MessageRegistry.set (D:\Users\%username%\.atom\packages\linter\lib\message-registry.js:56:18)
  at D:\Users\%username%\.atom\packages\linter\lib\linter.coffee:27:17
  at Emitter.module.exports.Emitter.emit (C:\Users\%username%\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
  at D:\Users\%username%\.atom\packages\linter\lib\linter-registry.js:98:29
```

Installed linter packages:
- linter 1.10.0
- linter-alex 1.5.0 (persists after updating to 1.5.1) 
- linter-htmlhint 0.2.1
- linter-php 1.1.0
- minimap-linter 1.0

Atom 1.1.0
Windows 7

**Comment by rugk** [comment]
Was fixed after restarting Atom.
I'll see if it comes back. If not I'll close this issue.

**Comment by wooorm** [comment]
I’m guessing the upgrade to 1.5.1 didn’t work until you restarted atom. 1.5.1 explicitly fixed this, so this issue is already fixed IMO.

**Comment by rugk** [comment]
Okay, good to hear.
