### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by RichardLitt** [wooorm/atom-linter-alex#37]
Any ideas?

```
11:19 ~/src/atom-linter-alex (master) * 🐕  npm run test

> linter-alex@4.0.0 test /Users/richard/src/atom-linter-alex
> npm run build && npm run lint && npm run test-api


> linter-alex@4.0.0 build /Users/richard/src/atom-linter-alex
> npm run build-md


> linter-alex@4.0.0 build-md /Users/richard/src/atom-linter-alex
> remark *.md -qfo


> linter-alex@4.0.0 lint /Users/richard/src/atom-linter-alex
> xo


> linter-alex@4.0.0 test-api /Users/richard/src/atom-linter-alex
> atom --test test/index.js

TAP version 13
# linter-alex
not ok 1 plan != count
  ---
    operator: fail
    expected: 2
    actual:   0
    at: process.<anonymous> (/Users/richard/src/atom-linter-alex/node_modules/tape/index.js:90:19)
    stack: |-
      Error: plan != count
          at Test.assert [as _assert] (/Users/richard/src/atom-linter-alex/node_modules/tape/lib/test.js:225:54)
          at Test.bound [as _assert] (/Users/richard/src/atom-linter-alex/node_modules/tape/lib/test.js:77:32)
          at Test.fail (/Users/richard/src/atom-linter-alex/node_modules/tape/lib/test.js:318:10)
          at Test.bound [as fail] (/Users/richard/src/atom-linter-alex/node_modules/tape/lib/test.js:77:32)
          at Test._exit (/Users/richard/src/atom-linter-alex/node_modules/tape/lib/test.js:185:14)
          at Test.bound (/Users/richard/src/atom-linter-alex/node_modules/tape/lib/test.js:77:32)
          at process.<anonymous> (/Users/richard/src/atom-linter-alex/node_modules/tape/index.js:90:19)
          at emitOne (events.js:101:20)
          at process.emit (events.js:191:7)
          at delayed (/Users/richard/src/atom-linter-alex/node_modules/atom-tap-test-runner/index.js:102:15)
          at once (/Users/richard/src/atom-linter-alex/node_modules/atom-tap-test-runner/index.js:163:7)
  ...

1..1
# tests 1
# pass  0
# fail  1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! linter-alex@4.0.0 test-api: `atom --test test/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the linter-alex@4.0.0 test-api script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/richard/.npm/_logs/2018-04-08T15_19_19_087Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! linter-alex@4.0.0 test: `npm run build && npm run lint && npm run test-api`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the linter-alex@4.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/richard/.npm/_logs/2018-04-08T15_19_19_137Z-debug.log
```

**Comment by wooorm** [comment]
Sorry it took a while, but I found it!

**Comment by RichardLitt** [comment]
Thank you!

**Comment by timofeysie** [comment]
What was the solution?  I have the same error!
