### ISSUE TITLE
Uncaught Error: Cannot find module './patterns.json'

### ISSUE THREAD

**Issue by liber-gong** [wooorm/atom-linter-alex#38]
Occur when installing this package:

**Atom**: 1.32.1 x64
**Electron**: 2.0.9
**OS**: Mac OS X 10.13.3
**Thrown From**: [linter-alex](https://github.com/get-alex/atom-linter-alex) package 5.0.1

### Stack Trace

Uncaught Error: Cannot find module './patterns.json'

```
At module.js:545

Error: Cannot find module './patterns.json'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:154368)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:145675)
    at /packages/linter-alex/node_modules/retext-equality/lib/index.js:13:16)
    at /packages/linter-alex/node_modules/retext-equality/lib/index.js:331:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:145675)
    at /packages/linter-alex/node_modules/parse-latin/index.js:2:18)
    at /packages/linter-alex/node_modules/parse-latin/index.js:4:3)
    at Module.get_Module._compile (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:146385)
    at Object.value [as .js] (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:145675)
    at loadOnce (/packages/linter-alex/index.js:100:14)
    at install (/packages/linter-alex/index.js:78:5)
```

### Commands

```
     -2:23.7.0 settings-view:open (input.hidden-input)
     -0:59.5.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-prettify 0.1.3 
atom-typescript 11.0.7 
busy-signal 1.4.3 
emmet 2.4.3 
esformatter 2.3.0 
file-type-icons 1.3.4 
intentions 1.1.5 
language-babel 2.81.1 
language-javascript-jsx 0.3.7 
language-svg 0.9.2 
language-vue 0.23.1 
linter 2.2.0 
linter-alex 5.0.1 
linter-ui-default 1.7.1 
markdown-scroll-sync 2.1.2 
monokai 0.24.0 
pretty-json 1.6.4 
raml 0.2.0 
script 3.18.1 
sync-settings 0.8.3 
```

Any ideas?

**Comment by wooorm** [comment]
@Mystist Thanks! I believe I pushed a fix to the correct project (retextjs/retext-equality). Installing again should fix this!

**Comment by liber-gong** [comment]
Can i have the fix commit? @wooorm

**Comment by wooorm** [comment]
There wasn’t a specific commit fixing this. The 3.5.0 release was just missing `patterns.json`, and [retext-equality@3.6.0](https://github.com/retextjs/retext-equality/releases) did include it.
