### ISSUE TITLE
Uncaught Error: Cannot find module 'remark-frontmatter'

### ISSUE THREAD

**Issue by manicmarvin** [wooorm/atom-linter-alex#39]
[Enter steps to reproduce:]

1. A project with several .md files was open.
2. Follow the prompt to update Alex to the latest version. 
3. Restart Atom.
4. Reopen the project.

Crash.

**Atom**: 1.33.0 x64
**Electron**: 2.0.11
**OS**: Mac OS X 10.13.6
**Thrown From**: [linter-alex](https://github.com/get-alex/atom-linter-alex) package 6.0.0

### Stack Trace

Uncaught Error: Cannot find module 'remark-frontmatter'

```
At module.js:545

Error: Cannot find module 'remark-frontmatter'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:154667)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:145974)
    at loadOnce (/packages/linter-alex/index.js:99:17)
    at install (/packages/linter-alex/index.js:79:5)
```

### Commands

```
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-ide-ui 0.13.0 
atom-jade 0.3.0 
atom-minify 0.8.0 
atom-sort-sass 0.2.1 
atom-sync 0.7.3 
autoclose-html 0.23.0 
busy-signal 1.4.3 
css-skeleton-maker 0.1.4 
cssnano 1.1.0 
custom-folds undefined 
dash 1.7.1 
dash-syntax 0.4.2 
dash-ui 0.4.4 
double-click-tree-view 1.1.0 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
fold-functions 0.11.0 
fold-navigator 0.0.622 
git-control 0.9.0 
git-tools 0.5.0 
highlight-selected 0.14.0 
html-to-css 0.2.2 
intentions 1.1.5 
javascript-snippets 1.2.1 
jquery-snippets 11.0.0 
language-mjml 2.0.1 
language-pug 0.0.22 
language-twig 1.6.3 
less-than-slash 0.18.0 
linter 2.2.0 
linter-alex 6.0.0 
linter-bootlint 1.1.0 
linter-csslint 2.0.1 
linter-htmlhint 1.5.1 
linter-htmllint 1.0.1 
linter-just-say-no 0.7.4 
linter-liferay 3.0.0 
linter-markdown 5.2.2 
linter-mjml 1.2.0 
linter-proselint 3.3.0 
linter-sass-lint 1.8.3 
linter-selective 0.3.1 
linter-tidy 2.3.1 
linter-twig 0.4.2 
linter-ui-default 1.7.1 
linter-write-good 0.9.0 
minimap 4.29.9 
minimap-bookmarks 0.4.2 
mjml-preview 2.0.1 
monokai-seti 0.9.0 
php-twig 4.0.0 
pigments 0.40.2 
remote-atom 1.3.12 
remote-ftp 2.2.2 
run-in-atom 1.0.5 
seti-ui 1.11.0 
spell-check-project 0.7.0 
todo-show 2.3.2 
v-bootstrap4 0.2.2 
```

**Comment by wooorm** [comment]
Whoops! Thanks, fixed!
