### ISSUE TITLE
Uncaught Error: Cannot find module 'alex/filter'

### ISSUE THREAD

**Issue by cubiczx** [wooorm/atom-linter-alex#40]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.0 x64
**Electron**: 2.0.11
**OS**: Ubuntu 18.04.1
**Thrown From**: [linter-alex](https://github.com/get-alex/atom-linter-alex) package 6.0.1

### Stack Trace

Uncaught Error: Cannot find module 'alex/filter'

```
At module.js:545

Error: Cannot find module 'alex/filter'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:154667)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:145974)
    at loadOnce (/packages/linter-alex/index.js:101:12)
    at install (/packages/linter-alex/index.js:79:5)
```

### Commands

```
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.4 
atom-updater-linux 1.3.0 
autoclose-html 0.23.0 
autocomplete-modules 2.2.6 
blade-snippets 0.2.0 
busy-signal 1.4.3 
docblockr 0.13.7 
editorconfig 2.2.2 
file-icons 2.1.26 
git-time-machine 2.1.0 
highlight-selected 0.14.0 
intentions 1.1.5 
jscs-fixer 1.3.0 
language-blade 0.41.4 
language-vue 0.23.1 
laravel-eloquent-snippets 2.0.0 
linter 2.2.0 
linter-alex 6.0.1 
linter-bootlint 1.1.0 
linter-csslint 2.0.1 
linter-eslint 8.4.1 
linter-htmlhint 1.5.1 
linter-jscs 4.1.3 
linter-jshint 3.1.9 
linter-jsonlint 1.3.0 
linter-markdown 5.2.2 
linter-php 1.5.1 
linter-phpcs 1.6.11 
linter-sass-lint 1.8.3 
linter-ui-default 1.7.1 
lorem 1.6.0 
php-cs-fixer 4.1.1 
pigments 0.40.2 
platformio-ide-terminal 2.8.4 
split-diff 1.5.3 
vue-autocomplete 0.1.1 
vue2-autocomplete 0.1.0-alpha.4 
```

**Comment by wooorm** [comment]
Sorry!

**Comment by cubiczx** [comment]
Thanks
