### ISSUE TITLE
Error: Expected node, got null

### ISSUE THREAD

**Issue by ben-eb** [wooorm/atom-linter-alex#5]
```
Error: Expected node, got null
  at Processor.run (/Users/beneb/.atom/packages/linter-alex/node_modules/alex/node_modules/retext/node_modules/unified/index.js:138:19)
  at /Users/beneb/.atom/packages/linter-alex/node_modules/alex/index.js:65:17
  at /Users/beneb/.atom/packages/linter-alex/node_modules/alex/node_modules/mdast/node_modules/unified/index.js:251:17
  at next (/Users/beneb/.atom/packages/linter-alex/node_modules/alex/node_modules/mdast/node_modules/ware/lib/index.js:82:27)
  at /Users/beneb/.atom/packages/linter-alex/node_modules/alex/node_modules/mdast/node_modules/ware/node_modules/wrap-fn/index.js:121:18
  at Ware.<anonymous> (/Users/beneb/.atom/packages/linter-alex/node_modules/alex/node_modules/mdast/node_modules/ware/node_modules/wrap-fn/index.js:83:42)
  at Ware.<anonymous> (/Users/beneb/.atom/packages/linter-alex/node_modules/alex/node_modules/mdast/node_modules/ware/node_modules/wrap-fn/index.js:57:27)
  at next (/Users/beneb/.atom/packages/linter-alex/node_modules/alex/node_modules/mdast/node_modules/ware/lib/index.js:85:20)
  at /Users/beneb/.atom/packages/linter-alex/node_modules/alex/node_modules/mdast/node_modules/ware/node_modules/wrap-fn/index.js:121:18
  at next (/Users/beneb/.atom/packages/linter-alex/node_modules/alex/node_modules/mdast/node_modules/ware/lib/index.js:82:27)
  at Of.Ware.run (/Users/beneb/.atom/packages/linter-alex/node_modules/alex/node_modules/mdast/node_modules/ware/lib/index.js:88:3)
  at Processor.run (/Users/beneb/.atom/packages/linter-alex/node_modules/alex/node_modules/mdast/node_modules/unified/index.js:149:23)
  at Ware.<anonymous> (/Users/beneb/.atom/packages/linter-alex/node_modules/alex/node_modules/mdast/node_modules/unified/index.js:30:21)
  at Ware.<anonymous> (/Users/beneb/.atom/packages/linter-alex/node_modules/alex/node_modules/mdast/node_modules/ware/node_modules/wrap-fn/index.js:45:19)
  at next (/Users/beneb/.atom/packages/linter-alex/node_modules/alex/node_modules/mdast/node_modules/ware/lib/index.js:85:20)
  at /Users/beneb/.atom/packages/linter-alex/node_modules/alex/node_modules/mdast/node_modules/ware/node_modules/wrap-fn/index.js:121:18
  at Ware.<anonymous> (/Users/beneb/.atom/packages/linter-alex/node_modules/alex/node_modules/mdast/node_modules/ware/node_modules/wrap-fn/index.js:83:42)
  at Ware.<anonymous> (/Users/beneb/.atom/packages/linter-alex/node_modules/alex/node_modules/mdast/node_modules/ware/node_modules/wrap-fn/index.js:57:27)
  at next (/Users/beneb/.atom/packages/linter-alex/node_modules/alex/node_modules/mdast/node_modules/ware/lib/index.js:85:20)
  at Ware.run (/Users/beneb/.atom/packages/linter-alex/node_modules/alex/node_modules/mdast/node_modules/ware/lib/index.js:88:3)
  at Processor.process (/Users/beneb/.atom/packages/linter-alex/node_modules/alex/node_modules/mdast/node_modules/unified/index.js:243:18)
  at alex (/Users/beneb/.atom/packages/linter-alex/node_modules/alex/index.js:60:14)
  at /Users/beneb/.atom/packages/linter-alex/index.js:102:28
  at Object.onchange [as lint] (/Users/beneb/.atom/packages/linter-alex/index.js:94:16)
  at Promise.then._this.emitter.emit.linter (/Users/beneb/.atom/packages/linter/lib/linter-registry.coffee:59:22)
  at LinterRegistry.triggerLinter (/Users/beneb/.atom/packages/linter/lib/linter-registry.coffee:58:16)
  at /Users/beneb/.atom/packages/linter/lib/linter-registry.coffee:52:17
  at Array.map (native)
  at /Users/beneb/.atom/packages/linter/lib/linter-registry.coffee:50:27
```

If it helps, the markdown I was editing: https://github.com/ben-eb/cssnano/blob/master/CHANGELOG.md

**Comment by wooorm** [comment]
Thanks for reporting! Any idea what you typed exactly?

**Comment by ben-eb** [comment]
I'm getting these no matter what I type, unfortunately; even just reading the file throws the error.

**Comment by wooorm** [comment]
@ben-eb Thanks for the quick response. Do you get it on other files?

**Comment by ben-eb** [comment]
Yeah. I think it's a regression in the latest release, because I've had no other problems with the linter so far. I updated atom before going to bed last night. :smile:

**Comment by wooorm** [comment]
:/

**Comment by wooorm** [comment]
Could you try uninstalling it, and installing it again? I updated `unified` to 2.0.0, and `retext` to 1.0.0, retext depends on unified@2.0.0 and mdast on unified@1.0.0. That’s probably it...

**Comment by ben-eb** [comment]
No dice, sorry. If it helps, my package list:

```
Sublime-Style-Column-Selection@1.3.0
Zen@0.16.2
cssnano@1.1.0
dracula-theme@0.7.6
dracula-ui@0.3.0
editorconfig@1.2.0
emmet@2.3.12
highlight-line@0.11.0
language-diff@0.3.1
linter@1.5.2
linter-alex@1.2.1
linter-eslint@3.0.2
linter-jshint@1.2.0
linter-stylelint@1.0.6
minimap@4.13.3
smart-tab-name@1.0.3
tabs-to-spaces@0.11.1
travis-ci-status@0.18.0
valign@1.1.3
vim-mode@0.60.0
wordcount@2.3.0
```

```
$ atom --version
1.0.13
```

**Comment by wooorm** [comment]
Thanks! I’ll look into it asap :)

**Comment by wooorm** [comment]
@ben-eb If you re-install now, it should work I think. It was fixed in alex’s code-base
I’ll push a version later anyway :)

**Comment by ben-eb** [comment]
That did the trick! Thanks. :+1:

**Comment by wooorm** [comment]
Great!
